library(rgdal)
library(dplyr)
setwd('~/Downloads/Extract_Data_Jun_11__2021__10_41_46_AM/')
release<-readOGR('Parasitoid_Release.shp')
recovery<-readOGR('Recovery.shp')
release@data$COUNT_OOBI<-as.numeric('release@data$COUNT_OOBI')
release@data$COUNT_OOBI<-as.numeric('release@data$COUNT_OOBI')

num_para<-release@data%>%group_by(SITE_ID)%>%summarise_if(is.numeric, sum)
length(unique(release$SITE_ID))
